###
DELETE http://localhost:8080/api/v1/article/2



###
GET http://localhost:8080/api/v1/article/
```
###
POST https://myshoppinglist-5c77ab8495cc.herokuapp.com/api/v1/article
Content-Type: application/json
{
        "name": "name1",
        "empty": "False"
}

###
GET https://localhost:8080/api/v1/article/
